# Crowdin Integration Configuration
# https://crowdin.com/

# IMPORTANT: Set these as environment variables or replace with actual values
project-id: "${CROWDIN_PROJECT_ID}"
api-token: "${CROWDIN_API_TOKEN}"

# Source language (must match Crowdin project settings)
source-language: pt-BR

# File patterns
files:
  # Source files pattern (where to find translation files)
  source-pattern: "languages/pt_br/**/*.yml"

  # Translation pattern (where to put downloaded translations)
  # %locale% = language code from Crowdin
  # %original_file_name% = original file name
  translation-pattern: "languages/%locale%/**/%original_file_name%"

# Preserve directory hierarchy
preserve-hierarchy: true

# Locale mapping (Crowdin locale -> AfterLanguage language code)
locale-mapping:
  "pt-BR": "pt_br"
  "en": "en_us"
  "es-ES": "es_es"
  "fr": "fr_fr"
  "de": "de_de"
  "it": "it_it"
  "ja": "ja_jp"
  "ko": "ko_kr"
  "zh-CN": "zh_cn"
  "zh-TW": "zh_tw"
  "ru": "ru_ru"

# Namespaces to sync (empty = sync all)
# Specify namespaces to limit sync to specific plugins
sync-namespaces: []
# Example: ['afterjournal', 'afterguilds']

# Upload settings
upload:
  # Auto-upload new source strings
  auto-upload: true

  # Update existing strings in Crowdin
  update-strings: true

  # Clean up (delete removed strings from Crowdin)
  cleanup-mode: false

  # Auto-approve translations uploaded via 'uploadtranslation' command
  # When true, uploaded translations skip the approval step on Crowdin
  auto-approve-imported: false

  # Automatically cleanup orphaned files after sync
  # When true, runs cleanup after successful sync to remove files/directories
  # that no longer exist locally. Requires server-id configured for safety.
  cleanup-on-sync: false

# Download settings
download:
  # Skip untranslated strings (use fallback instead)
  skip-untranslated: true

  # Export only approved translations
  export-approved-only: true

# Advanced settings
advanced:
  # Batch size for API requests
  batch-size: 100

  # Request timeout (seconds)
  timeout-seconds: 30

  # Retry attempts on failure
  max-retries: 3
